---
- name: Check if node is already in cluster
  shell: kubectl get nodes
  environment:
    KUBECONFIG: /etc/kubernetes/kubelet.conf
  register: node_status
  failed_when: false
  changed_when: false

- name: Copy join command
  copy:
    src: "{{ playbook_dir }}/join_command.sh"
    dest: /tmp/join_command.sh
    mode: '0755'
  when: node_status.rc != 0

- name: Join cluster
  shell: /tmp/join_command.sh
  when: node_status.rc != 0

- name: Remove join command
  file:
    path: /tmp/join_command.sh
    state: absent

- name: Verify node joined
  shell: kubectl get nodes {{ ansible_hostname }}
  environment:
    KUBECONFIG: /etc/kubernetes/kubelet.conf
  retries: 10
  delay: 5
  when: node_status.rc != 0
