{{- if and .Values.analytics.enabled .Values.analytics.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "webapp-stack.fullname" . }}-analytics-hpa
  labels:
    {{- include "webapp-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "webapp-stack.fullname" . }}-analytics
  minReplicas: {{ .Values.analytics.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.analytics.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.analytics.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.analytics.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
