{{- if .Values.analytics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "webapp-stack.fullname" . }}-analytics
  labels:
    {{- include "webapp-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
spec:
  type: {{ .Values.analytics.service.type }}
  ports:
    - port: {{ .Values.analytics.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "webapp-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: analytics
{{- end }}
