---
- name: Setup Kubernetes Cluster
  hosts: all
  become: yes
  roles:
    - common
    - docker
    - kubernetes

- name: Initialize Kubernetes Master
  hosts: masters
  become: yes
  roles:
    - kubernetes-master

- name: Join Kubernetes Workers
  hosts: workers
  become: yes
  roles:
    - kubernetes-worker
